# train multiple replicates using the best hyperparameters found during hyperparameter optimization
chemprop train \
	--epochs 50 \
	--patience 5 \
	--num-workers 1 \
	--data-seed 42 \
	--pytorch-seed 42 \
	--data-path ../train.csv \
    --task-type regression \
	--smiles-columns SMILES \
	--target-columns LogD KSOL \
	--output-dir output_train \
	--split-type random \
	--split-sizes 0.90 0.10 0.00 \
    --num-replicates 5 \
	--loss mse \
	--metrics mse mae rmse r2 \
	--molecule-featurizers rdkit_2d \
    --message-hidden-dim 1200 \
    --warmup-epochs 12 \
    --final-lr 0.0000277 \
    --batch-size 64 \
    --aggregation sum \
    --max-lr 0.0002 \
    --activation LEAKYRELU \
    --depth 4 \
    --dropout 0.0 \
    --ffn-num-layers 1 \
    --ffn-hidden-dim 400 \
    --init-lr 0.0000511
