chemprop train \
	--from-foundation output_pretrain/model_0/best.pt \
	--ffn-num-layers 1 \
	--ffn-hidden-dim 2048 \
	--batch-size 64 \
	--epochs 50 \
	--patience 5 \
	--num-workers 1 \
	--data-seed 42 \
	--pytorch-seed 42 \
	--data-path ../train_LogD.csv \
	--smiles-columns SMILES \
	--target-columns LogD \
	--output-dir output_train \
	--split-type random \
	--split-sizes 0.80 0.20 0.00 \
    --num-replicates 5 \
	--loss mse \
	--metrics mse mae rmse r2 \
	--molecule-featurizers morgan_count rdkit_2d
